name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # 3. Install Android SDK command-line tools
      - name: Install Android SDK command-line tools
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          cd "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O sdk-tools.zip
          unzip -q sdk-tools.zip
        env:
          ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk

      # 4. Accept licenses & install platform-tools and build-tools
      - name: Accept SDK licenses and install packages
        run: |
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${{ env.ANDROID_SDK_ROOT }}" \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;31.0.0"
        env:
          ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk

      # 5. Install system Gradle
      - name: Install Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      # 6. Build the Debug APK
      - name: Build Debug APK
        run: gradle -p app assembleDebug --no-daemon --stacktrace

      # 7. Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
