name: Build Android APK

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # 3. Install Android SDK tools
      - name: Install Android SDK command-line tools
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          cd "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O tools.zip
          unzip -q tools.zip
        env:
          ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk

      # 4. Accept licenses & install platform-tools & build-tools
      - name: Accept SDK licenses & install packages
        run: |
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${{ env.ANDROID_SDK_ROOT }}" \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;31.0.0"
        env:
          ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk

      # 5. Install system Gradle
      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      # 6. Build the APK
      - name: Build Debug APK
        run: gradle -p app assembleDebug --no-daemon --stacktrace

      # 7. Upload the APK as artifact using v1
      - name: Upload APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
